version: 2.0
jobs:
  build:
    working_directory: ~/ahr
    docker:
      - image: circleci/python:2.7
      #- image: circleci/ruby:2.4.2-jessie-node
      # - image: alpine:3.7
      # - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get install ruby
            pip install --upgrade pip
  print:
    docker:
      - image: circleci/python:2.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - print

#pip install --upgrade pip
#pip install python-coveralls pycrypto MySQL-python --user
#gem update --system
#gem install sass
#gem install compass
#curl -o $HOME/google_appengine_1.9.40.zip https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.49.zip
#unzip -q -d $HOME $HOME/google_appengine_1.9.40.zip
