version: 2.0
jobs:
  build:
    working_directory: ~/ahr
    docker:
      - image: circleci/python:2.7
      #- image: circleci/ruby:2.4.2-jessie-node
      # - image: alpine:3.7
      # - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Install Ruby
          command: |
            apt-get install ruby-dev
      # - run:
      #     name: Install Pips
      #     command: |
      #       pip install --upgrade pip
      #       pip install python-coveralls pycrypto MySQL-python --user

      - run:
          name: Install Gems
          command: |
            # gem update --system
            sudo gem install compass
  print:
    docker:
      - image: circleci/python:2.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - print:
          requires:
            - build


#gem install sass
#gem install compass
#curl -o $HOME/google_appengine_1.9.40.zip https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.49.zip
#unzip -q -d $HOME $HOME/google_appengine_1.9.40.zip
